### ISSUE TITLE
Cannot run this on latest node version. 

### ISSUE THREAD

**Issue by EdSouthgateBR** [onehungrymind/angular-reactive-workshop#52]
Just thought I'd let you know that I ran into the following issue running this on the latest version of node 18.16.0. Downgrading to v12.0.0 fixed the issue I also let FEM know so they can add a note or something to the course if necessary. Thanks for the awesome courses by the way. :) 
 
```
npm run start

> angular-core-workshop@0.0.0 start
> concurrently "npm run server" "ng serve"

[0] 
[0] > angular-core-workshop@0.0.0 server
[0] > json-server server/db.json
[0]
[0] 
[0]   \{^_^}/ hi!
[0]
[0]   Loading server/db.json
[0]   Done
[0] 
[0]   Resources
[0]   http://localhost:3000/customers
[0]   http://localhost:3000/projects
[0]
[0]   Home
[0]   http://localhost:3000
[0]
[0]   Type s + enter at any time to create a snapshot of the database
[1] Browserslist: caniuse-lite is outdated. Please run next command `npm update`
[1] i ｢wds｣: Project is running at http://localhost:4200/webpack-dev-server/
[1] i ｢wds｣: webpack output is served from /
[1] i ｢wds｣: 404s will fallback to //index.html
[1] node:internal/crypto/hash:71
[1]   this[kHandle] = new _Hash(algorithm, xofLen);
[1]                   ^
[1]
[1] Error: error:0308010C:digital envelope routines::unsupported
[1]     at new Hash (node:internal/crypto/hash:71:19)
[1]     at Object.createHash (node:crypto:133:10)
[1]     at module.exports (C:\Users\EdSouthgate\source\repos\angular-reactive-workshop\node_modules\webpack\lib\util\createHash.js:135:53)
[1]     at NormalModule._initBuildHash (C:\Users\EdSouthgate\source\repos\angular-reactive-workshop\node_modules\webpack\lib\NormalModule.js:412:16)
[1]     at C:\Users\EdSouthgate\source\repos\angular-reactive-workshop\node_modules\webpack\lib\NormalModule.js:444:10
[1]     at C:\Users\EdSouthgate\source\repos\angular-reactive-workshop\node_modules\webpack\lib\NormalModule.js:320:13
[1]     at C:\Users\EdSouthgate\source\repos\angular-reactive-workshop\node_modules\loader-runner\lib\LoaderRunner.js:367:11
[1]     at C:\Users\EdSouthgate\source\repos\angular-reactive-workshop\node_modules\loader-runner\lib\LoaderRunner.js:203:19
[1]     at VirtualFileSystemDecorator.readFile (C:\Users\EdSouthgate\source\repos\angular-reactive-workshop\node_modules\@ngtools\webpack\src\virtual_file_system_decorator.js:46:13)
[1]     at processResource (C:\Users\EdSouthgate\source\repos\angular-reactive-workshop\node_modules\loader-runner\lib\LoaderRunner.js:202:11)
[1]     at iteratePitchingLoaders (C:\Users\EdSouthgate\source\repos\angular-reactive-workshop\node_modules\loader-runner\lib\LoaderRunner.js:158:10)
[1]     at runLoaders (C:\Users\EdSouthgate\source\repos\angular-reactive-workshop\node_modules\loader-runner\lib\LoaderRunner.js:365:2)
[1]     at NormalModule.doBuild (C:\Users\EdSouthgate\source\repos\angular-reactive-workshop\node_modules\webpack\lib\NormalModule.js:292:3)
[1]     at NormalModule.build (C:\Users\EdSouthgate\source\repos\angular-reactive-workshop\node_modules\webpack\lib\NormalModule.js:438:15)
[1]     at Compilation.buildModule (C:\Users\EdSouthgate\source\repos\angular-reactive-workshop\node_modules\webpack\lib\Compilation.js:702:10)
[1]     at C:\Users\EdSouthgate\source\repos\angular-reactive-workshop\node_modules\webpack\lib\Compilation.js:944:14 {
[1]   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
[1]   library: 'digital envelope routines',
[1]   reason: 'unsupported',
[1]   code: 'ERR_OSSL_EVP_UNSUPPORTED'
[1] }
[1]
[1] Node.js v18.16.0
[1] ng serve exited with code 1
```

**Comment by kowalkos** [comment]
same here any update?

**Comment by dtauer** [comment]
Yes, this is a known issue. To run the application, you'll need to use Node version 12. We recommend using a Node version manager like [nvm](https://github.com/nvm-sh/nvm).
